name: CMIP6 IOMB
on: workflow_dispatch
jobs:
  run_config:
    runs-on: ubuntu-latest
    steps:
      - name: Run rsync job
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: gadi.nci.org.au
          username: ${{secrets.GADI_USER}}
          key: ${{secrets.DEPLOY_KEY}}
          command_timeout: 600m
          script: |
            cd ${{secrets.GADI_SCRIPTS_DIR}}/../ILAMB/script_github_ilamb
            cd iomb_CMIP6_access
            qsub pbs.job
